#include <iostream>
#include <fstream>
#include <string.h>
#include <algorithm>
#include <map>
#include <vector>
#include <stdexcept>

struct static_help_t {
  const char * cmd_name;
  const char * cmd_howto;
  const char * cmd_syntax;
  const char * cmd_related;
  const char * cmd_examples;
};

const static_help_t static_help[] = {
#include "static_helpen.h"
};

const int static_help_size = sizeof(static_help) / sizeof(static_help_t);
using namespace std;

// Offsets keep every string in read-only storage, including shared suffixes.
// No decoding buffer or allocation is needed on the calculator.
void output_compact(const char * filename) {
  vector<vector<string>> rows;
  map<string, unsigned> offsets;
  for (int i = 0; i < static_help_size; ++i) {
    const static_help_t & h = static_help[i];
    const char * fields[] = {h.cmd_name, h.cmd_howto, h.cmd_syntax, h.cmd_related, h.cmd_examples};
    vector<string> row;
    for (const char * field : fields) {
      row.push_back(field ? field : "");
      offsets[row.back()] = 0;
    }
    rows.push_back(row);
  }
  // Binary lookup requires bytewise ordering; keep the first duplicate entry.
  stable_sort(rows.begin(), rows.end(),
              [](const vector<string> & a, const vector<string> & b) { return a[0] < b[0]; });
  vector<string> strings;
  for (const auto & entry : offsets)
    strings.push_back(entry.first);
  sort(strings.begin(), strings.end(), [](const string & a, const string & b) {
    return a.size() != b.size() ? a.size() > b.size() : a < b;
  });
  string pool(1, '\0');
  for (const string & s : strings) {
    if (s.empty() || offsets[s])
      continue;
    unsigned start = pool.size();
    pool += s;
    pool += '\0';
    for (unsigned i = 0; i < s.size(); ++i) {
      auto found = offsets.find(s.substr(i));
      if (found != offsets.end() && !found->second)
        found->second = start + i;
    }
  }
  if (pool.size() >= (1u << 19))
    throw runtime_error("Compact help exceeds 19-bit offsets");
  ofstream out(filename);
  out << "// Generated by mkhelp; byte offsets into immutable text.\n"
         "static const char compact_help_text[] =\n";
  for (unsigned i = 0; i < pool.size(); ++i) {
    if (i % 32 == 0)
      out << '"';
    unsigned char c = pool[i];
    out << '\\' << char('0' + (c >> 6)) << char('0' + ((c >> 3) & 7)) << char('0' + (c & 7));
    if (i % 32 == 31 || i + 1 == pool.size())
      out << "\"\n";
  }
  out << ";\nstatic const struct { unsigned short offsets[5], banks; } compact_help_rows[] = {\n";
  for (const auto & row : rows) {
    out << "{{";
    unsigned banks = 0;
    for (unsigned column = 0; column < row.size(); ++column) {
      unsigned offset = offsets.at(row[column]);
      if (column)
        out << ',';
      out << (offset & 65535);
      banks |= (offset >> 16) << (3 * column);
    }
    out << "}," << banks << "},\n";
  }
  out << "};\n";
  if (!out)
    throw runtime_error("Unable to write compact help");
}

int main() {
  output_compact("compact_helpen.h");
}
